# Generated by Django 6.0.2 on 2026-03-27 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEngagementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('lesson_minutes', models.PositiveIntegerField(default=0)),
                ('live_session_minutes', models.PositiveIntegerField(default=0)),
                ('assessment_minutes', models.PositiveIntegerField(default=0)),
                ('ai_messages', models.PositiveIntegerField(default=0)),
                ('flashcard_minutes', models.PositiveIntegerField(default=0)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_engagement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_a5c356_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lesson_view', 'Lesson View'), ('live_session', 'Live Session Watch'), ('assessment', 'Assessment Attempt'), ('ai_chat', 'AI Chat Message'), ('flashcard_study', 'Flashcard Study')], db_index=True, max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('resource_label', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'event_date'], name='analytics_e_user_id_1c28b1_idx'), models.Index(fields=['event_type', 'event_date'], name='analytics_e_event_t_7a4962_idx'), models.Index(fields=['user', 'resource_id', 'event_type'], name='analytics_e_user_id_8914e7_idx')],
            },
        ),
    ]
