# Generated by Django 4.2.29 on 2026-04-03 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('lesson_view', 'Lesson View'), ('live_session', 'Live Session Watch'), ('assessment', 'Assessment Attempt'), ('ai_chat', 'AI Chat Message'), ('flashcard_study', 'Flashcard Study'), ('lesson_complete', 'Lesson Complete'), ('assessment_pass', 'Assessment Pass'), ('assessment_fail', 'Assessment Fail'), ('login', 'Login'), ('recording_view', 'Recording View'), ('chatroom_msg', 'Chat Message'), ('competition', 'Competition'), ('streak_break', 'Streak Break'), ('notification_click', 'Notification Click'), ('page_visit', 'Page Visit')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
