# Generated by Django 6.0.2 on 2026-03-23 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='academics.section')),
            ],
            options={
                'ordering': ['section__classroom__name', 'section__name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatrooms.chatroom')),
            ],
            options={
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['room', 'sent_at'], name='chatrooms_c_room_id_860d77_idx'), models.Index(fields=['room', 'is_pinned'], name='chatrooms_c_room_id_edf5d5_idx')],
            },
        ),
    ]
