# Generated by Django 6.0.2 on 2026-03-23 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('class_general', 'Class General'), ('subject', 'Subject'), ('staff', 'Staff'), ('officials', 'Officials')], db_index=True, max_length=16)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_chat_rooms', to='academics.institution')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='academics.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='academics.subject')),
            ],
            options={
                'ordering': ['room_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('attachment_type', models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File')], max_length=10, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chatrooms.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatrooms.chatroom')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'section'], name='chatrooms_c_room_ty_3880bb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'institution'], name='chatrooms_c_room_ty_bb202e_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'class_general')), fields=('section',), name='unique_class_general_per_section'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'subject')), fields=('section', 'subject'), name='unique_subject_room_per_section_subject'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'staff')), fields=('institution',), name='unique_staff_room_per_institution'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'sent_at'], name='chatrooms_c_room_id_860d77_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'parent'], name='chatrooms_c_room_id_1c44c2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'is_pinned'], name='chatrooms_c_room_id_edf5d5_idx'),
        ),
    ]
