# Generated by Django 6.0.2 on 2026-03-17 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('announcement', 'Announcement'), ('assessment', 'Assessment'), ('lesson', 'Lesson')], db_index=True, default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('announcement', 'Announcement'), ('assessment', 'Assessment'), ('lesson', 'Lesson')], db_index=True, default='info', max_length=20)),
                ('audience_type', models.CharField(choices=[('direct', 'Direct (single user)'), ('class_all', 'Entire class (students + teachers)'), ('class_students', 'Class — students only'), ('class_teachers', 'Class — teachers only'), ('school_all', 'Whole school'), ('school_students', 'School — students only'), ('school_teachers', 'School — teachers only'), ('district_all', 'Entire district'), ('district_students', 'District — students only'), ('district_teachers', 'District — teachers only'), ('district_principals', 'District — principals only'), ('system', 'System-wide')], default='direct', max_length=30)),
                ('audience_label', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('attachment_url', models.URLField(blank=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.broadcast'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['sender', '-sent_at'], name='notificatio_sender__bf2505_idx'),
        ),
    ]
