# Generated by Django 6.0.2 on 2026-03-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_user_id_d7f78b_idx',
            old_name='notifications_p_user_id_idx',
        ),
    ]
