# Generated by Django 6.0.2 on 2026-02-22 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subject_course'),
        ('content', '0002_alter_course_options_alter_lessonprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.subject'),
        ),
    ]
