# Generated by Django 6.0 on 2026-01-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_lessonprogress_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='last_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.lesson'),
        ),
    ]
