# Generated by Django 6.0 on 2026-01-04 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_lessonprogress_time_spent_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='time_spent_seconds',
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('lesson', 'user'), name='unique_lesson_progress_per_user'),
        ),
    ]
