# Generated by Django 6.0.2 on 2026-03-26 20:34

import apps.livesessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='public_id',
            field=models.CharField(db_index=True, default=apps.livesessions.models.generate_public_id, max_length=20, unique=True),
        ),
    ]
