# Generated by Django 4.2.29 on 2026-04-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesessions', '0002_livesession_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='recording_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_egress_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_r2_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['section', 'recording_status', '-scheduled_at'], name='livesession_section_d94324_idx'),
        ),
    ]
