# Generated by Django 6.0.2 on 2026-02-21 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_course_options_alter_lessonprogress_options_and_more'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['name'], 'verbose_name': 'Learning Path', 'verbose_name_plural': 'Learning Paths'},
        ),
        migrations.RemoveConstraint(
            model_name='learningpathcourse',
            name='unique_course_per_learning_path',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningpathcourse',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='learning.learningpath'),
        ),
        migrations.AlterField(
            model_name='learningpathcourse',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='learningpathcourse',
            constraint=models.UniqueConstraint(fields=('learning_path', 'course'), name='unique_course_in_path'),
        ),
        migrations.AddConstraint(
            model_name='learningpathcourse',
            constraint=models.UniqueConstraint(fields=('learning_path', 'order'), name='unique_order_in_path'),
        ),
    ]
