# Generated by Django 6.0.2 on 2026-03-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincode',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.district'),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('OFFICIAL', 'Official')], max_length=16),
        ),
    ]
