# Generated by Django 6.0 on 2026-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('OFFICIAL', 'Official'), ('ADMIN', 'Admin')], default='STUDENT', max_length=16),
        ),
    ]
