# Generated by Django 6.0.2 on 2026-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_number',
            new_name='mobile_primary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_secondary',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
