# Generated by Django 6.0.2 on 2026-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_classroom_teachers_remove_user_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
