# Generated by Django 6.0.2 on 2026-02-20 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_district_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 2, 20)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='otpverification',
            unique_together={('user', 'date')},
        ),
    ]
