# Generated by Django 6.0.2 on 2026-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpverification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
