# Generated by Django 6.0.2 on 2026-02-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_otpverification_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='otpverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Verification', 'verbose_name_plural': 'OTP Verifications'},
        ),
        migrations.AlterUniqueTogether(
            name='otpverification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='date',
        ),
    ]
