# Generated by Django 6.0.2 on 2026-02-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_classroom_options_and_more'),
        ('content', '0002_alter_course_options_alter_lessonprogress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.course'),
        ),
    ]
