# Generated by Django 6.0.2 on 2026-02-14 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentattempt_questionoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
