# Generated by Django 6.0.2 on 2026-02-21 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessmentattempt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.RenameField(
            model_name='assessmentattempt',
            old_name='answers',
            new_name='selected_options',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentattempt',
            unique_together={('user', 'assessment', 'submitted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('assessment', 'order')},
        ),
    ]
