# Generated by Django 6.0.2 on 2026-03-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='academics_s_name_b0c3fe_idx'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.section'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['name', 'district'], name='academics_i_name_110778_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'district')},
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['institution', 'name'], name='academics_c_institu_d83bf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'institution')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['classroom', 'name'], name='academics_s_classro_3fba6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='studentsubject',
            index=models.Index(fields=['student', 'subject'], name='academics_s_student_fc4a51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['classroom', 'subject'], name='academics_c_classro_da60fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('classroom', 'subject')},
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['teacher', 'subject', 'section'], name='academics_t_teacher_7e2b60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'subject', 'section')},
        ),
    ]
