# Generated by Django 6.0.2 on 2026-03-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.section'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('classroom', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'subject', 'section')},
        ),
    ]
