# Generated by Django 6.0.2 on 2026-03-23 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished')], db_index=True, default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Optional: when the room is scheduled to go live.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(help_text='Questions are drawn from this assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='competition_rooms', to='assessments.assessment')),
                ('host', models.ForeignKey(limit_choices_to={'role__in': ['TEACHER', 'PRINCIPAL', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_competitions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(help_text='Only students in this section can join.', on_delete=django.db.models.deletion.CASCADE, related_name='competition_rooms', to='academics.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='competition_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competitionroom')),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chosen_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_answers', to='assessments.questionoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_answers', to='assessments.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_answers', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='competitions.competitionroom')),
            ],
        ),
        migrations.AddIndex(
            model_name='competitionroom',
            index=models.Index(fields=['section', 'status'], name='competition_section_486849_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionroom',
            index=models.Index(fields=['host', '-created_at'], name='competition_host_id_de6314_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionparticipant',
            index=models.Index(fields=['room', '-score'], name='competition_room_id_548cc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionparticipant',
            unique_together={('room', 'student')},
        ),
        migrations.AddIndex(
            model_name='competitionanswer',
            index=models.Index(fields=['room', 'student'], name='competition_room_id_4f238a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionanswer',
            unique_together={('room', 'student', 'question')},
        ),
    ]
