# Generated by Django 4.2.29 on 2026-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionroom',
            name='time_limit_secs',
            field=models.PositiveIntegerField(default=60, help_text='Time per question in seconds.'),
        ),
    ]
