# Generated by Django 6.0.2 on 2026-03-16 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[('lesson_complete', 'Lesson completed'), ('assessment_attempt', 'Assessment attempted'), ('assessment_pass', 'Assessment passed'), ('perfect_score', 'Perfect score (100%)'), ('streak_3', '3-day streak bonus'), ('streak_7', '7-day streak bonus')], max_length=32)),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('assessment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveSmallIntegerField(default=0)),
                ('longest_streak', models.PositiveSmallIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_code', models.CharField(choices=[('first_lesson', 'First Lesson'), ('lesson_10', '10 Lessons Completed'), ('lesson_50', '50 Lessons Completed'), ('first_pass', 'First Assessment Passed'), ('perfect_score', 'Perfect Score'), ('streak_3', '3-Day Streak'), ('streak_7', '7-Day Streak'), ('points_100', '100 Points'), ('points_500', '500 Points')], max_length=32)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['earned_at'],
                'unique_together': {('user', 'badge_code')},
            },
        ),
    ]
