# Generated by Django 6.0.2 on 2026-03-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gradeentry',
            new_name='gradebook_g_student_901ddb_idx',
            old_name='gradebook_g_student_8a3c1f_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeentry',
            new_name='gradebook_g_entered_116ecf_idx',
            old_name='gradebook_g_entered_b7d2e4_idx',
        ),
    ]
