# Generated by Django 6.0.2 on 2026-03-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('role', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=16)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'Join Code',
                'verbose_name_plural': 'Join Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
