# Generated by Django 6.0.2 on 2026-02-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0001_initial'),
        ('accounts', '0009_alter_classroom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joincode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Join Code', 'verbose_name_plural': 'Join Codes'},
        ),
        migrations.AlterField(
            model_name='joincode',
            name='code',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_join_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='expires_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_codes', to='accounts.institution'),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='is_used',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_codes', to='accounts.section'),
        ),
    ]
